// <auto-generated />
using System;
using DPNS.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DPNS.Migrations
{
    [DbContext(typeof(DpnsDbContext))]
    [Migration("20260113173004_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DPNS.Entities.App", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("app_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("time with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("projects_pk");

                    b.HasIndex(new[] { "AppName" }, "projects_unique")
                        .IsUnique();

                    b.HasIndex(new[] { "Guid" }, "projects_unique_uuid")
                        .IsUnique();

                    b.ToTable("apps", (string)null);
                });

            modelBuilder.Entity("DPNS.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppId")
                        .HasColumnType("integer")
                        .HasColumnName("app_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("project_users_pk");

                    b.HasIndex("AppId");

                    b.HasIndex("UserId");

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("DPNS.Entities.PushNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUrl")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("app_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("push_notifications_pk");

                    b.ToTable("push_notifications", (string)null);
                });

            modelBuilder.Entity("DPNS.Entities.PushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("AppId")
                        .HasColumnType("integer")
                        .HasColumnName("app_id");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("auth");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("endpoint");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("p256dh");

                    b.HasKey("Id")
                        .HasName("push_subscriptions_pk");

                    b.HasIndex("AppId");

                    b.ToTable("push_subscriptions", (string)null);
                });

            modelBuilder.Entity("DPNS.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("time with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("time with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnType("character varying")
                        .HasColumnName("password");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("users_pk");

                    b.HasIndex(new[] { "Email" }, "users_unique")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DPNS.Entities.UserVerificationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("verification_code");

                    b.HasKey("Id")
                        .HasName("user_verification_tokens_pk");

                    b.HasIndex("UserId");

                    b.ToTable("user_verification_tokens", (string)null);
                });

            modelBuilder.Entity("DPNS.Entities.AppUser", b =>
                {
                    b.HasOne("DPNS.Entities.App", "App")
                        .WithMany("AppUsers")
                        .HasForeignKey("AppId")
                        .IsRequired()
                        .HasConstraintName("app_users_apps_fk");

                    b.HasOne("DPNS.Entities.User", "User")
                        .WithMany("AppUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("app_users_users_fk");

                    b.Navigation("App");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DPNS.Entities.PushSubscription", b =>
                {
                    b.HasOne("DPNS.Entities.App", "App")
                        .WithMany("PushSubscriptions")
                        .HasForeignKey("AppId")
                        .IsRequired()
                        .HasConstraintName("push_subscriptions_apps_fk");

                    b.Navigation("App");
                });

            modelBuilder.Entity("DPNS.Entities.UserVerificationToken", b =>
                {
                    b.HasOne("DPNS.Entities.User", "User")
                        .WithMany("UserVerificationTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("user_verification_tokens_users_fk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DPNS.Entities.App", b =>
                {
                    b.Navigation("AppUsers");

                    b.Navigation("PushSubscriptions");
                });

            modelBuilder.Entity("DPNS.Entities.User", b =>
                {
                    b.Navigation("AppUsers");

                    b.Navigation("UserVerificationTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
