@DPNS_HostAddress = http://localhost:32770

POST {{DPNS_HostAddress}}/api/subscription/
Accept: application/json
Content-Type: application/json

{
  "endpoint": "https://example.com/abcdef",
  "auth": "5q3n7J6EgyVAb6pgE",
  "P256DH": "BDRd50z5ESS32mFqaLVJIT-Ap-EgwELoHWo2BFa5_oZSGHKLtQcM3w4-nEA2XOnM6QMN1zYApbs4SjjQgt56rQk"
}

###

POST {{DPNS_HostAddress}}/api/notification/
Accept: application/json
Content-Type: application/json

{
  "title": "test",
  "text": "This is a test notification!"
}

###
