@DPNS_HostAddress = http://subnodulous-kaelyn-matrimonially.ngrok-free.dev
@authToken = 
@appGuid = a3143c93-5dc7-412f-95e5-4c0d08e4a8c6

# @name registration
POST {{DPNS_HostAddress}}/api/auth/register
Accept: application/json
Content-Type: application/json

{
  "name": "tester",
  "email": "tester@gmail.com",
  "password": "123456"
}

###

POST {{DPNS_HostAddress}}/api/auth/verify-email
Accept: application/json
Content-Type: application/json

{
  "verificationCode": "/8OiWPl9IkOZDtuo4j4Skg=="
}

### 

# @name Login
POST {{DPNS_HostAddress}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "tester2@gmail.com",
  "password": "123456"
}

###

@authToken = {{Login.response.body.$.token}}

###

POST {{DPNS_HostAddress}}/api/app/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "appName": "Turtle Quest test",
  "url": "https://turtle-questtest.vercel.app"
}

###

POST {{DPNS_HostAddress}}/api/subscription/?appId={{appGuid}}
Accept: application/json
Content-Type: application/json

{
  "endpoint": "https://wns2-db5p.notify.windows.com/w/?token=BQYAAAA%2fCSShMAjWDJXRuPGsryANKHFuVcqJtKpYZ3Eo%2bctLY6CRh1p8h1eWI8lcLd1kuI71NNzwmZg2DzmClH%2bqMnS7aNVe3XCBqCzR98%2by%2bAYjwaL%2fraaiBAGoUzEObzM78lQTP5Nz%2bJzDvUou1T3%2fe%2bez9MbHBK8f1M9L4HSDPSqS0Q464%2bhexW%2feTPaDNwHKxH3SpylRf4bFk4HWymOSKyMiDDAiSCO6jtazL27KhqXtMEu5yJnPo%2bHIpO%2bfZBvXUY1xdrLpfWoBAYFL2ogoM%2f5opTnSd5n2mZkMJuP4coRPt1yJfnwDx7h6yvQvL8%2fhb7k%3d",
  "keys": {
    "auth": "mvkuL7zhDhoAWMjQ1cmYcw",
    "P256DH": "BNNZoX6cmkCtM3Ib8OGVfslVAmCsL6q-dMEm6TdW6rkraE9TUO9fGmu8bvGokEL7AjgnrncMStJndym1IrlSQng"
  }
}

###

POST {{DPNS_HostAddress}}/api/notification/?appid={{appGuid}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "test turtle",
  "text": "turtles are super cute!!"
}

###

GET {{DPNS_HostAddress}}/api/app/
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

POST {{DPNS_HostAddress}}/api/app/add-user/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "appGuid": "{{appGuid}}",
  "email": "tester@gmail.com"
}

###

DELETE {{DPNS_HostAddress}}/api/app/{{appGuid}}/remove-user/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "email": "tester@gmail.com"
}

###

GET {{DPNS_HostAddress}}/api/app/{{appGuid}}/subscription-count/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

DELETE {{DPNS_HostAddress}}/api/app/{{appGuid}}/
Content-Type: application/json
Authorization: Bearer {{authToken}}

###